Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Documents\GitHub\Web-Project\web-project\calculator\views_wiki.py", line 35, in menu
    requestJson(request)
  File "C:\Users\PC\Documents\GitHub\Web-Project\web-project\calculator\function.py", line 191, in requestJson
    number_request = int(request_json_file['user'][i]['number_request']) + 1
                         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: list indices must be integers or slices, not dict
